version: '3.8'

services:
  api:
    image: git.neolegal.fr/neolegal/namorama-api:latest
    restart: unless-stopped
    environment:
      DATABASE_URL: mysql://${MARIADB_USER}:${MARIADB_PASSWORD}@192.168.1.95:3306/namorama
      KEYCLOAK_AUTH_SERVER_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: namorama
      KEYCLOAK_CLIENT_ID: namorama-api
      KEYCLOAK_SECRET: ${KEYCLOAK_SECRET}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      FRONTEND_URL: ${FRONTEND_URL}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
      STRIPE_PACK_DECOUVERTE_PRICE_ID: ${STRIPE_PACK_DECOUVERTE_PRICE_ID}
      STRIPE_PACK_PRO_PRICE_ID: ${STRIPE_PACK_PRO_PRICE_ID}
      STRIPE_PACK_MAX_PRICE_ID: ${STRIPE_PACK_MAX_PRICE_ID}
    ports:
      - "127.0.0.1:3000:3000"

  web:
    image: git.neolegal.fr/neolegal/namorama-web:latest
    restart: unless-stopped
    environment:
      API_URL: ${API_URL}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
    ports:
      - "127.0.0.1:8088:80"
    depends_on:
      - api
