server {
    listen 80;
    server_name namorama-api.neolegal.fr;
    return 301 https://api.namorama.com$request_uri;
}

server {
    listen 443 ssl;
    server_name namorama-api.neolegal.fr;

    ssl_certificate     /etc/letsencrypt/live/neolegal.fr/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/neolegal.fr/privkey.pem;

    return 301 https://api.namorama.com$request_uri;
}
